// <auto-generated />
using System;
using Infraestructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240619174735_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name")
                        .HasColumnOrder(10);

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Price")
                        .HasColumnOrder(20);

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ab3b69ed-dca0-429b-932f-21954265990f"),
                            Name = "Potato",
                            Price = 1.05m
                        },
                        new
                        {
                            Id = new Guid("ec78609d-51e3-44a6-9776-abf5f0e8802b"),
                            Name = "Coca Cola",
                            Price = 2.10m
                        },
                        new
                        {
                            Id = new Guid("0bf6b028-6cff-4271-bf94-37b5f3c3744f"),
                            Name = "Onion",
                            Price = 0.50m
                        },
                        new
                        {
                            Id = new Guid("4493afc2-ce99-418a-a0c1-1d9656f27c05"),
                            Name = "Bread",
                            Price = 0.80m
                        },
                        new
                        {
                            Id = new Guid("cd3c1122-f460-4125-ae0a-53d4b09365b4"),
                            Name = "Meat",
                            Price = 4.15m
                        },
                        new
                        {
                            Id = new Guid("3fdff7e9-5ad5-415e-94bb-9f8bd5dabc10"),
                            Name = "Rice",
                            Price = 1.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
