// <auto-generated />
using System;
using Infraestructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name")
                        .HasColumnOrder(10);

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Price")
                        .HasColumnOrder(20);

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("747a5828-debe-4bfd-a407-bb6334edd647"),
                            Name = "Potato",
                            Price = 1.05m
                        },
                        new
                        {
                            Id = new Guid("56b71d61-d9c9-4350-8722-9cbf5c983e5a"),
                            Name = "Coca Cola",
                            Price = 2.10m
                        },
                        new
                        {
                            Id = new Guid("a1957ca6-66bf-47d6-9f6b-4e0f4a27e961"),
                            Name = "Onion",
                            Price = 0.50m
                        },
                        new
                        {
                            Id = new Guid("c219cbf9-1518-486c-97f1-28c5cc472be4"),
                            Name = "Bread",
                            Price = 0.80m
                        },
                        new
                        {
                            Id = new Guid("6a33b04d-67d8-43a4-91e3-3f1bf73f5860"),
                            Name = "Meat",
                            Price = 4.15m
                        },
                        new
                        {
                            Id = new Guid("b620a89d-e67e-45f1-a39f-005868409fa0"),
                            Name = "Rice",
                            Price = 1.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
